import { Agent } from "./arc";

export const DEMO_AGENTS: Agent[] = [
  {
    id: "1",
    owner: "0x1A2B3c4D5e6F7a8B9c0D1E2F3a4B5c6D7e8F9a0B",
    metadataURI: "ipfs://bafkreibdi6623n3xpf7ymk62ckb4bo75o3qemwkpfvp5i25j66itxvsoei",
    metadata: {
      name: "DeFi Arbitrage Agent v1.0",
      description: "Autonomous trading agent for cross-DEX arbitrage on Arc. Monitors price discrepancies across liquidity pools and executes trades within milliseconds.",
      agent_type: "trading",
      capabilities: ["arbitrage_detection", "liquidity_monitoring", "automated_execution"],
      version: "1.0.0",
      price_usdc: 25,
    },
    reputation: 94,
    feedbackCount: 127,
    isVerified: true,
    tags: ["successful_trade", "low_slippage", "kyc_verified"],
  },
  {
    id: "2",
    owner: "0x2B3c4D5e6F7a8B9c0D1E2F3a4B5c6D7e8F9a0B1C",
    metadataURI: "ipfs://example2",
    metadata: {
      name: "Yield Optimizer Pro",
      description: "Automatically rebalances yield farming positions across Arc-native protocols to maximize APY while managing risk exposure.",
      agent_type: "yield",
      capabilities: ["yield_farming", "auto_rebalance", "risk_management"],
      version: "2.3.1",
      price_usdc: 15,
    },
    reputation: 88,
    feedbackCount: 84,
    isVerified: true,
    tags: ["yield_farming", "rebalance", "kyc_verified"],
  },
  {
    id: "3",
    owner: "0x3C4d5E6f7A8b9C0d1E2f3A4b5C6d7E8f9A0b1C2D",
    metadataURI: "ipfs://example3",
    metadata: {
      name: "NFT Sniper Bot",
      description: "Monitors NFT marketplaces for undervalued listings and executes purchases based on rarity scores and floor price analysis.",
      agent_type: "nft",
      capabilities: ["nft_monitoring", "rarity_analysis", "floor_tracking"],
      version: "1.1.0",
      price_usdc: 10,
    },
    reputation: 76,
    feedbackCount: 42,
    isVerified: true,
    tags: ["nft_purchase", "below_floor", "successful_trade"],
  },
  {
    id: "4",
    owner: "0x4D5e6F7a8B9c0D1E2F3a4B5c6D7e8F9a0B1c2D3E",
    metadataURI: "ipfs://example4",
    metadata: {
      name: "Liquidity Guardian",
      description: "Manages concentrated liquidity positions in AMM pools, adjusting ranges to stay in-range and collect maximum fees.",
      agent_type: "liquidity",
      capabilities: ["range_management", "fee_collection", "impermanent_loss_control"],
      version: "3.0.2",
      price_usdc: 35,
    },
    reputation: 97,
    feedbackCount: 203,
    isVerified: true,
    tags: ["liquidity_management", "fee_optimization", "kyc_verified"],
  },
  {
    id: "5",
    owner: "0x5E6f7A8b9C0d1E2f3A4b5C6d7E8f9A0b1C2d3E4F",
    metadataURI: "ipfs://example5",
    metadata: {
      name: "Risk Sentinel",
      description: "Monitors wallet exposure and automatically hedges positions when risk thresholds are breached. 24/7 portfolio protection.",
      agent_type: "risk",
      capabilities: ["risk_monitoring", "auto_hedge", "alert_system"],
      version: "1.4.0",
      price_usdc: 20,
    },
    reputation: 91,
    feedbackCount: 156,
    isVerified: true,
    tags: ["risk_management", "hedge", "kyc_verified"],
  },
  {
    id: "6",
    owner: "0x6F7a8B9c0D1E2F3a4B5c6D7e8F9a0B1c2D3e4F5A",
    metadataURI: "ipfs://example6",
    metadata: {
      name: "Cross-Chain Bridge Scout",
      description: "Finds the cheapest and fastest bridge routes across chains, executes multi-hop transfers to minimize fees and slippage.",
      agent_type: "bridge",
      capabilities: ["route_optimization", "multi_hop", "fee_comparison"],
      version: "0.9.5",
      price_usdc: 8,
    },
    reputation: 65,
    feedbackCount: 18,
    isVerified: false,
    tags: ["bridge", "cross_chain"],
  },
];
